#!/usr/bin/env python3
"""
Bundles all tweets in data/ into a single self-contained HTML file
that can be opened directly without any server.
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data"
WEB_DIR = ROOT / "web"
OUTPUT = WEB_DIR / "standalone.html"


def load_all_snapshots() -> list[dict]:
    """Reads index.json and loads every referenced snapshot file."""
    index_file = DATA_DIR / "index.json"
    if not index_file.exists():
        return []

    with open(index_file, "r", encoding="utf-8") as f:
        index = json.load(f)

    snapshots = []
    for entry in index:
        snap_path = ROOT / entry["file"]
        if not snap_path.exists():
            continue
        with open(snap_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        snapshots.append({
            "meta": entry,
            "data": data,
        })
    return snapshots


def build():
    snapshots = load_all_snapshots()

    template = (WEB_DIR / "index.html").read_text(encoding="utf-8")
    css = (WEB_DIR / "styles.css").read_text(encoding="utf-8")
    app_js = (WEB_DIR / "app.js").read_text(encoding="utf-8")

    # Inline CSS
    template = template.replace(
        '<link rel="stylesheet" href="styles.css">',
        f"<style>\n{css}\n</style>",
    )

    # Replace external app.js with an inlined version that uses embedded data
    inline_data_js = (
        "// Embedded data — generated by scripts/build_standalone.py\n"
        f"const EMBEDDED_SNAPSHOTS = {json.dumps(snapshots, ensure_ascii=False)};\n\n"
    )

    # Patch the app's init() to use embedded data instead of fetch
    patched_js = app_js.replace(
        'const INDEX_URL = "../data/index.json";',
        'const INDEX_URL = null;  // unused in standalone mode',
    ).replace(
        "async function init() {\n"
        "  try {\n"
        "    const resp = await fetch(INDEX_URL);\n"
        "    if (!resp.ok) throw new Error(`No se pudo leer ${INDEX_URL}`);\n"
        "    allSnapshots = await resp.json();\n"
        "  } catch (e) {\n"
        "    showError(`Error cargando index.json: ${e.message}. Recuerda servir el repo con un servidor HTTP (p.ej. <code>python -m http.server</code>).`);\n"
        "    return;\n"
        "  }",
        "async function init() {\n"
        "  allSnapshots = EMBEDDED_SNAPSHOTS.map(s => s.meta);"
    ).replace(
        "    try {\n"
        "      const resp = await fetch(`../${s.file}`);\n"
        "      const data = await resp.json();\n"
        "      for (const t of data.tweets) {\n"
        "        all.push({ ...t, _source: data.source, _fetched_at: data.fetched_at });\n"
        "      }\n"
        "    } catch (e) {\n"
        "      console.error(`Failed to load ${s.file}:`, e);\n"
        "    }",
        "    const bundle = EMBEDDED_SNAPSHOTS.find(b => b.meta.file === s.file);\n"
        "    if (bundle) {\n"
        "      for (const t of bundle.data.tweets) {\n"
        "        all.push({ ...t, _source: bundle.data.source, _fetched_at: bundle.data.fetched_at });\n"
        "      }\n"
        "    }",
    )

    template = template.replace(
        '<script src="app.js"></script>',
        f"<script>\n{inline_data_js}{patched_js}\n</script>",
    )

    # Drop the local-server hint, since this version runs without a server
    template = template.replace(
        "<small>Datos cargados desde <code>data/</code>. Para servir local: <code>python -m http.server</code> desde la raíz del repo.</small>",
        f"<small>Versión autocontenida — {len(snapshots)} snapshots embebidos.</small>",
    )

    OUTPUT.write_text(template, encoding="utf-8")
    total_tweets = sum(s["data"]["count"] for s in snapshots)
    size_kb = OUTPUT.stat().st_size / 1024
    print(f"Built {OUTPUT.relative_to(ROOT)}")
    print(f"  {len(snapshots)} snapshots, {total_tweets} tweets, {size_kb:.1f} KB")


if __name__ == "__main__":
    build()
