#!/usr/bin/env python3
"""
Bundles all tweets in data/ into a single self-contained HTML file
that can be opened directly without any server. The app.js is left
unchanged; we inject a fetch() shim that serves the embedded data
when fetch is called with a path inside data/.
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data"
WEB_DIR = ROOT / "web"
OUTPUT = WEB_DIR / "standalone.html"


def load_all_snapshots() -> dict:
    """Reads every snapshot file referenced by index.json into a dict
    keyed by relative path (so the fetch shim can look them up)."""
    index_file = DATA_DIR / "index.json"
    if not index_file.exists():
        return {"index": [], "snapshots": {}}

    with open(index_file, "r", encoding="utf-8") as f:
        index = json.load(f)

    snapshots = {}
    for entry in index:
        snap_path = ROOT / entry["file"]
        if not snap_path.exists():
            continue
        with open(snap_path, "r", encoding="utf-8") as f:
            snapshots[entry["file"]] = json.load(f)

    return {"index": index, "snapshots": snapshots}


FETCH_SHIM = """
// --- standalone fetch shim: serve embedded data for ../data/* URLs ---
const __ORIG_FETCH = window.fetch.bind(window);
window.fetch = async function (url, opts) {
  const u = String(url);
  if (u.endsWith('/data/index.json') || u === '../data/index.json') {
    return new Response(JSON.stringify(__EMBEDDED.index), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });
  }
  // Match anything that looks like a data/<...>.json path
  const m = u.match(/(?:\\.\\.\\/)?(data\\/[^?#]+\\.json)$/);
  if (m) {
    const key = m[1];
    if (__EMBEDDED.snapshots[key]) {
      return new Response(JSON.stringify(__EMBEDDED.snapshots[key]), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      });
    }
  }
  return __ORIG_FETCH(url, opts);
};
"""


def build():
    bundle = load_all_snapshots()
    template = (WEB_DIR / "index.html").read_text(encoding="utf-8")
    css = (WEB_DIR / "styles.css").read_text(encoding="utf-8")
    app_js = (WEB_DIR / "app.js").read_text(encoding="utf-8")

    # Inline CSS
    template = template.replace(
        '<link rel="stylesheet" href="styles.css">',
        f"<style>\n{css}\n</style>",
    )

    # Inject embedded data + fetch shim, then the original app.js
    embedded_block = (
        "// --- embedded data, generated by scripts/build_standalone.py ---\n"
        f"const __EMBEDDED = {json.dumps(bundle, ensure_ascii=False)};\n"
        f"{FETCH_SHIM}\n"
    )
    template = template.replace(
        '<script src="app.js"></script>',
        f"<script>\n{embedded_block}\n{app_js}\n</script>",
    )

    # Update footer hint
    template = template.replace(
        "<small>Datos cargados desde <code>data/</code>. Para servir local: <code>python -m http.server</code> desde la raíz del repo.</small>",
        f"<small>Versión autocontenida — {len(bundle['snapshots'])} snapshots embebidos.</small>",
    )

    OUTPUT.write_text(template, encoding="utf-8")
    total_tweets = sum(s["count"] for s in bundle["snapshots"].values())
    size_kb = OUTPUT.stat().st_size / 1024
    print(f"Built {OUTPUT.relative_to(ROOT)}")
    print(f"  {len(bundle['snapshots'])} snapshots, {total_tweets} tweets, {size_kb:.1f} KB")


if __name__ == "__main__":
    build()
